name: LLM_therapist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - requests
  - openai
  - pip:
    - torch
    - transformers
    - datasets
    - accelerate
    - bitsandbytes
    - peft
    - trl
